### ISSUE TITLE
ipam allocation not successful

### ISSUE THREAD

**Issue by PallaviTharigonda** [cisco-app-networking/nsm-nse#75]
Hi ,
  I'm getting some errors because of IPAM
time="2021-06-07T10:10:58Z" level=error msg="ipam allocation not successful: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup ipam-vl3-service.wcm-cisco.com on 10.100.0.10:53: no such host\" \n waiting 60 seconds before retrying \n"
time="2021-06-07 10:11:04.20089" level=info msg="Agent plugin state update." lastErr="<nil>" loc="statuscheck/plugin_impl_statuscheck.go(183)" logger=status-check plugin=vpp-ifplugin state=ok

What are the possibilities of the issue??

**Comment by nishantapatil3** [comment]
We moved to private repo long time ago

**Comment by PallaviTharigonda** [comment]
sure thank you @nishantapatil3
